# Öğretmen (Claude) tarafından yazılmış, kaynaklı Türkçe özetler.
# Fine-tune eğitim verisinin "hedef çıktı" kısmı; kaynaklar = kaynaklar.jsonl.
# Her özet YALNIZCA ilgili varyantın kaynaklarına dayanır.

OZETLER = {

"BRAF V600E": """BRAF V600E, MAPK sinyal yolunu düzenleyen BRAF proteininde görülen ve birçok kanserde tanısal, prognostik ve öngörücü bir biyobelirteç olarak kabul edilen bir mutasyondur [4]. 2002'de çeşitli kanserlerde BRAF mutasyonları tanımlanmış, sonrasında V600E'yi hedefleyen küçük moleküllü inhibitörler geliştirilmiştir [4].

Farklı kanser türlerinde görülür: Ameloblastomda yapılan bir meta-analizde (833 vaka) BRAF V600E sıklığı %70,49 bulunmuş; 54 yaş altı hastalarda ve mandibula (alt çene) yerleşiminde anlamlı biçimde daha sık saptanmıştır [1]. Papiller tiroid karsinomunda en yaygın onkojenik sürücüdür; MAPK yolunu aktive eder ve iyot metabolizması ile farklılaşma genlerini baskılar [3]. Gliomlarda en sık görülen BRAF değişimidir; özellikle çocukluk çağı düşük dereceli astrositomları, pleomorfik ksantoastrositom, papiller kraniofarinjiom, epiteloid glioblastom ve gangliogliomda ortaya çıkar [5].

Tedavi açısından, vemurafenib, dabrafenib ve selumetinib gibi seçici BRAF ve MEK inhibitörleri ileri tiroid kanserlerinde etkinlik göstermiştir; dabrafenib-trametinib kombinasyonu BRAF V600E'li anaplastik tiroid karsinomu için FDA onaylıdır [3]. Ancak kolon kanserinde BRAF V600E inhibisyonu, EGFR'nin geri besleme yoluyla aktivasyonu nedeniyle sınırlı yanıt verir; bu tümörler BRAF ve EGFR inhibitörlerinin birlikte kullanımından fayda görebilir [2]. Melanom hücreleri EGFR'yi düşük eksprese ettiğinden bu geri besleme direncine daha az maruz kalır [2]. Mutasyon durumu genellikle PCR temelli DNA testleriyle belirlenir; 2011'den beri BRAF V600E'ye özgü antikorlar (klon VE1) immünohistokimyasal değerlendirmeye olanak tanır [4].""",

"EGFR L858R": """EGFR L858R, küçük hücreli dışı akciğer kanserinde (KHDAK) en sık görülen onkojenik sürücülerden biri olan EGFR gen mutasyonudur [1]. EGFR mutasyonları Asya kökenli hastalarda (%30-50), Kafkas kökenlilere göre (%10-15) daha sıktır [1]. Ekson 19 delesyonu (Ex19del) ve L858R nokta mutasyonu, klasik aktive edici mutasyonların büyük çoğunluğunu oluşturur ve EGFR tirozin kinaz inhibitörlerine (TKİ) iyi klinik yanıtın güçlü öngörücüleridir [2].

L858R, TKİ tedavisine artmış duyarlılık anlamına gelse de belirgin bir yanıtsızlık oranı da vardır [5]. Klinik davranış Ex19del ile L858R arasında farklılık gösterir ve sonuçların Ex19del hastalarında daha iyi olabileceği giderek kabul görmektedir [1][4]. İkinci nesil geri dönüşümsüz bir TKİ olan dakomitinib bu hastalarda araştırılmaktadır [1].

Direnç açısından, TKİ tedavisi sırasında en sık ikincil T790M mutasyonu ile direnç gelişir; EAI045 gibi allosterik inhibitörler L858R/T790M mutantını hedeflerken yaban tip reseptörü korur ve setuksimab ile belirgin sinerji gösterir [3]. L858R tespiti çoğunlukla DNA temellidir; ancak mutasyonu mRNA düzeyinde çok yüksek duyarlılıkla (%0,01) saptayan RT-PCR yöntemleri de geliştirilmiştir [5].""",

"EGFR T790M": """EGFR T790M, akciğer kanserinde birinci nesil EGFR tirozin kinaz inhibitörlerine (gefitinib, erlotinib, afatinib) karşı kazanılmış direncin en sık nedenidir [1][5]. Reseptörün ATP bölgesinde yer alan bu ikincil mutasyon, kazanılmış dirençli hastaların yaklaşık yarısında bulunur ve reseptörün ATP'ye afinitesini artırarak TKİ'lerin bağlanmasını zorlaştırır [4]. T790M ayrıca kanser hücrelerine büyüme avantajı sağlayarak bir "çifte rol" oynayabilir [4].

Tedavide üçüncü nesil TKİ osimertinib, T790M mutasyonlu metastatik KHDAK için onay alan ilk ilaçtır [2]. FLAURA çalışmasında osimertinib, birinci basamakta birinci nesil TKİ'lere göre daha uzun progresyonsuz sağkalım sağlamış ve beyin metastazlarında da umut verici etkinlik göstermiştir [5]. Ancak osimertinib tedavisi sırasında da direnç gelişir; en sık üçlü mutasyonla (duyarlılaştıran mutasyon/T790M/C797S) ortaya çıkar ve mevcut tüm EGFR TKİ'lerine dirençlidir [1][5].

Bu üçlü mutantlara karşı EAI045 gibi allosterik inhibitörler ve Del19/T790M/C797S'yi hedefleyen CH7233163 gibi yeni bileşikler geliştirilmektedir [1][3]. MET amplifikasyonu ve IGF1R aktivasyonu ise EGFR TKİ'lerine karşı alternatif direnç mekanizmaları olarak bildirilmiştir [4].""",

"KRAS G12C": """KRAS, kanserde en sık mutasyona uğrayan onkogendir; G12C ise ileri, skuamöz olmayan KHDAK'te en sık görülen KRAS varyantıdır (~%40) ve bu tümörlerin %10-13'ünü oluşturur [2]. G12C mutantı, kovalent inhibitör tasarımına olanak tanıyan bir sistein kalıntısı taşır [1].

Tedavide AMG 510 (sotorasib), klinik geliştirmeye giren ilk KRAS G12C inhibitörüdür; preklinik çalışmalarda tümör gerilemesi sağlamış, immün-yeterli farelerde kalıcı yanıtlar oluşturmuş ve immün kontrol noktası inhibitörleriyle sinerji göstermiştir [1]. Sotorasib ve adagrasib, ileri/metastatik KHDAK için ikinci basamak ve sonrasında onaylanmıştır [2]. Adagrasib, KHDAK ve kolorektal kanser dışındaki KRAS G12C'li solid tümörlerde (pankreas, safra yolu dahil) yaklaşık %35 objektif yanıt oranıyla etkinlik göstermiştir [5].

Direnç açısından, KHDAK'in aksine kolorektal kanser G12C inhibitörlerine nadiren yanıt verir; başlıca neden EGFR sinyalinin yeniden aktive olmasıdır ve EGFR ile G12C'nin birlikte hedeflenmesi direnci aşar [4]. Erken adaptif direnç, başta EGFR olmak üzere reseptör tirozin kinazların ve MRAS:SHOC2:PP1C kompleksinin aktivasyonuyla oluşur [3]. STK11, KEAP1 ve TP53 sık görülen ko-mutasyonlardır; STK11 birlikteliği immünoterapinin etkisini zayıflatabilir [2][3].""",

"KRAS G12D": """KRAS G12D, solid tümörlerde en sık görülen onkojenik KRAS alt tipidir ve klinikte uzun süre "ilaçlanamaz" olarak kabul edilmiştir [2]. Özellikle pankreas adenokarsinomlarının (PDAK) neredeyse yarısında bulunur [1].

Tedavi geliştirmede MRTX1133, ilk güçlü, seçici ve kovalent olmayan KRAS G12D inhibitörüdür; GDP-bağlı KRAS G12D'ye çok yüksek afinite gösterir ve yaban tipe kıyasla yaklaşık 700 kat seçicidir [3][4]. ERK1/2 fosforilasyonunu ve KRAS G12D-mutant hücrelerin canlılığını baskılar; PDAK modellerinin çoğunda (11 modelin 8'inde) tümör gerilemesi sağlar [3].

Pankreas kanseri modellerinde MRTX1133, tümör mikroçevresini yeniden programlayarak tümör içi CD8+ efektör T hücrelerini artırır, miyeloid infiltrasyonu azaltır ve immün kontrol noktası blokajı ile sinerji göstererek sağkalımı uzatır; ileri PDAK'in gerilemesi CD8+ T hücrelerine bağımlıdır ve KRAS G12D inhibisyonu kanser hücrelerinde FAS ifadesini indükleyerek T hücresi aracılı ölümü kolaylaştırır [1]. Bir diğer inhibitör HRS-4642 faz 1'de umut verici antitümör aktivitesi göstermiş, proteazom inhibisyonu (karfilzomib) ile etkinliği artmıştır [2]. EGFR veya PI3Kα gibi geri besleme/baypas yollarının birlikte hedeflenmesi antitümör etkiyi güçlendirir [3].""",

"TP53 R175H": """TP53, kanserde en sık mutasyona uğrayan sürücü gendir; R175H (175. pozisyondaki arjininin histidinle yer değiştirmesi) en yüksek sıklıkta görülen TP53 sıcak nokta mutasyonudur [1][5]. Yaban tip p53 "genomun bekçisi" olarak DNA onarımı, hücre döngüsü durması ve apoptozu tetiklerken, R175H bu işlevleri kaybeder ve kanseri destekleyen yeni işlevler (proliferasyon, göç, invazyon, ilaç direnci) kazanır [5].

Mekanizma açısından R175H dominant-negatif ve onkojenik aktiviteye sahiptir; agregasyona eğilimlidir ve birçok proteinle etkileşerek onkojenik işlev kazanır [4][5]. Meme kanserinde CORO1A-P38 MAPK yolunu düzenleyerek hücre çoğalmasını artırır; TP53 mutasyonları üçlü-negatif meme kanserinde daha sıktır ve R175H taşıyan hastaların sağkalımı daha kısadır [2]. Pankreas kanseri modellerinde TP53(R175H), sitoplazmik SOX9 lokalizasyonunu indükler ve bu durum mortaliteyle ilişkilidir [3].

Tedavide, mutant p53'ün ilaçlanabilir bir aktif bölgesinin olmaması hedeflemeyi zorlaştırır [4]. Yaklaşımlar arasında R175H'ye özgü bir antikorun, T hücrelerini aktive eden biespesifik bir immünoterapötik ajana dönüştürülmesi [1] ve p53-R175H'yi seçici olarak yıkan bir PROTAC (dp53m) yer alır; dp53m yaban tip p53'ü korurken antitümör etkinlik göstermiş ve sisplatine duyarlılığı artırmıştır [4].""",

"JAK2 V617F": """JAK2 V617F, miyeloproliferatif neoplazilerde (MPN) en yaygın sürücü mutasyondur; JAK/STAT sinyal yolunu sitokinlerden bağımsız olarak sürekli aktive eder ve hastalığın başlangıcı ile ilerlemesinde önemli rol oynar [1]. JAK/STAT dışında hücre çoğalması, farklılaşma, anti-apoptoz ve DNA hasarı birikimi gibi süreçleri de çeşitli yollarla etkiler [1].

JAK inhibitörleri klinikte yaygın kullanılsa da MPN hücrelerini kökten yok edemez; bu nedenle uzun süreli tedavi gerekir ve inhibitörlerin diğer ilaçlarla birlikte kullanımı araştırılmaktadır [1]. V617F, nötrofillere özgü ifade edildiğinde (CALR mutasyonundan farklı olarak) IL-1 dahil pro-inflamatuar sitokinleri indükler ve nötrofillerde belirgin bir inflamatuar kemokin imzası oluşturur; bu, MPN'deki inflamasyonun önemli bir sürücüsüdür [2]. Ayrıca VLA4 integrin aracılı yapışkan bir fenotip yaratarak trombotik riske katkıda bulunabilir [2].

Kardiyovasküler açıdan JAK2 V617F, klonal hematopoez bağlamında miyokard enfarktüsü riskini artırır; özellikle plak erozyonuyla güçlü ilişkilidir (OR 16,2), plak rüptürüyle ise anlamlı ilişki göstermez [4]. Bu ilişkiye, taşıyıcı nötrofillerin aktivasyon, adezyon ve migrasyon genlerini artırması katkıda bulunabilir [4]. JAK2 rs10974944 polimorfizmi isehem V617F-pozitif hem de V617F-negatif MPN ile ilişkili bulunmuştur [5].""",

"PIK3CA H1047R": """PIK3CA H1047R, PI3K enziminin katalitik alt birimini (p110α) kodlayan PIK3CA genindeki en sık görülen sıcak nokta mutasyondur ve meme kanserinde tüm PIK3CA mutasyonlarının yaklaşık üçte birini (%35) oluşturur [1]. Meme kanseri hastalarının yaklaşık %36'sı PIK3CA-mutant tümör taşır; bu mutasyonlar hormon reseptörü pozitif/HER2-negatif alt tipte (%42), üçlü-negatif alt tipe (%16) göre daha sıktır [1]. İleri PIK3CA-mutant meme kanserinde therascreen tanı testi ve alfa-özgül PI3K inhibitörü alpelisib onaylıdır; ancak bu panel, bilinen PIK3CA-mutant hastaların yaklaşık %20'sini yakalayamaz [1].

Mekanizma açısından p110α'nın H1047R mutantı PI3K-AKT yolunu sürekli aktive eder ve MCF-10A hücrelerini dönüştürerek SNAIL indüksiyonu ve E-kaderin kaybıyla epitel-mezenkimal geçişe (EMT) yol açar [5]. Üçlü-negatif meme kanserinde bildirilen sıcak nokta mutasyondur ve hedefe yönelik ilaç geliştirmek için hesaplamalı yöntemlerle doğal bileşikler taranmaktadır [3]. Hindistan'daki baş-boyun skuamöz hücreli karsinom hastalarında %52 sıklıkta saptanmış ve mutasyon taşıyanlarda genel ve progresyonsuz sağkalım daha kısa bulunmuştur (kötü prognoz) [4].

Kanser dışında da önemi vardır: somatik H1047R mutasyonu PI3Kα-AKT-mTOR yolunu aşırı aktive ederek venöz malformasyonlara neden olur; fare modellerinde mTOR blokajının etkisi sınırlı kalırken TIE2 veya ANGPT hedeflenmesi lezyon büyümesini baskılamıştır [2].""",

"NRAS Q61R": """NRAS Q61R, RAS/MAPK sinyal yolunu aktive eden NRAS genindeki bir mutasyondur ve melanomda en sık ikinci onkojenik sürücü olan NRAS Q61* mutasyonları arasında yer alır [4]. Hücrelerde ERK fosforilasyonunu artırarak MAPK/ERK yolunu aşırı aktive eder [1].

Tanıda NRAS Q61R immünohistokimyası, tiroid patolojisinde RAS Q61R mutasyonunu saptamada yüksek duyarlılık (%90,6) ve özgüllük (%92,3) gösterir; ancak antikor NRAS, KRAS ve HRAS Q61R proteinlerine çapraz reaksiyon verir ve en sık papiller tiroid karsinomunun foliküler varyantında pozitiftir [2].

Damar ve deri hastalıklarında da rol oynar: NRAS Q61R insan endotel hücrelerinde iğ şeklinde morfoloji, artmış çoğalma ve göçe yol açarak damar malformasyonlarına neden olur; MEK inhibitörü U0126 bu değişimi önlerken mTOR inhibitörü rapamisin önlememiştir [1]. Mutasyon, endotel hücrelerinde anjiopoietin-2 (Ang-2) ifadesini artırır ve bu artışın baskılanmasında MEK inhibitörü trametinib rapamisinden daha etkilidir [3]. Konjenital melanositik nevüslerde en sık görülen değişimdir (%61,8) ve NRAS p.Q61R/K alel yükü lezyon büyüklüğü, renk değişkenliği ve hipertrikoz gibi fenotiplerle ilişkilidir [5].

Tedavi geliştirmede NRAS Q61* mutantlarını seçici hedefleyen klinik ajanlar henüz yoktur; ancak NRAS Q61R ile doğrudan etkileşen SHOC2-MRAS-PP1C kompleksinin bir bileşeni olan SHOC2, RAS Q61* tümörleri için bir bağımlılık olarak tanımlanmış ve SHOC2-RAS etkileşimini bozan küçük moleküller geliştirilmiştir [4].""",

"IDH1 R132H": """IDH1 R132H, izositrat dehidrogenaz 1 enziminin 132. kodonundaki arjininin histidinle değişmesiyle oluşan ve difüz gliomlarda en sık görülen IDH1 mutasyonudur [2]. Bu kazanılmış-işlev (gain-of-function) mutasyonu, onkometabolit (R)-2-hidroksiglutarat üretimine yol açarak çeşitli kanserlerin gelişimine katkıda bulunur [3].

Glioma biyolojisinde R132H, Dünya Sağlık Örgütü derece II-III ve sekonder gliomlarda en sık mutasyona uğrayan gendir ve daha iyi prognozla ilişkilidir [4][5]. Glioblastom modellerinde IDH1-R132H hücre çoğalmasını, göçü ve invazyonu azaltır, apoptozu artırır ve temozolomid sitotoksisitesini güçlendirir; bu etkiyi kısmen FAT1-ROS-HIF-1α sinyal yolu üzerinden gösterir [5]. Ayrıca DNA çift-zincir kırıklarının onarımını geciktirip TIGAR ifadesini epigenetik olarak baskılayarak glioma hücrelerini radyoterapiye duyarlı hale getirir [4].

Tedavi yaklaşımları açısından R132H, MHC sınıf II üzerinde sunulan ortak bir neoepitop taşır; buna yönelik IDH1(R132H)-özgül peptit aşısı, yeni tanı almış derece 3-4 astrositomlu hastalarda faz I çalışmasında güvenli bulunmuş ve hastaların %93,3'ünde bağışıklık yanıtı oluşturmuştur; üç yıllık progresyonsuz sağkalım oranı 0,63 idi [2]. Mutant enzimin aktivitesi C269 kalıntısındaki otopalmitoilasyonla düzenlenir ve bu bölge, klinik bir IDH1-mutant inhibitörünün (LY3410738) hedefidir [3]. Öte yandan IDH1-R132H, sisplatinle tetiklenen ferroptozu artırarak akut böbrek hasarına yatkınlığı yükseltebilir [1].""",

"KIT D816V": """KIT D816V, tip III tirozin kinaz reseptörü KIT'te görülen ve mastositoz ile mast hücresi aktivasyon sendromlarının (MCAS) tanı ve sınıflandırmasında temel taşı olan bir mutasyondur [1]. Mutasyon reseptörü sürekli (konstitütif) aktif hale getirir; yaban tip KIT ligand bağlanmasıyla dimerleşirken, D816V mutantı dimerleşmeden aktive olur ve tirozin kinaz alanının kararlılığı azalır [2]. D816V, yaban tip reseptörle benzer sinyal yollarını hedeflese de sinyali daha güçlü iletir ve mastositozda sık bozulan yolları (enfeksiyon ilişkili yollar, spliseozom) aktive eder [2].

Tanıda KIT D816V, deri lezyonu olmayan hastalarda kanda veya kemik iliğinde düşük mutant hücre yükü nedeniyle saptanamayabilir; bu nedenle ultra-duyarlı yöntemler gereklidir [1]. Yeni Flow-SuperRCA testi, geleneksel ASO-qPCR'a göre daha duyarlıdır (saptama sınırı %0,001'e karşı %0,01 alel sıklığı) ve monoklonal MCAS hastalarının %64'ünde pozitiflik saptamıştır [1]. Anafilaksi veya sistemik mast hücresi aktivasyonu olan hastalarda periferik kanda KIT D816V prevalansı %4 bulunmuştur [5].

Tedavide patojenik C-KIT D816V mutasyonunun hedeflenmesi sistemik mastositoz tedavisini dönüştürmüştür; avapritinib bu alanda hastalığı değiştirebilen ilk ruhsatlı ilaçtır ve bezuklastinib ile elenestinib gibi giderek daha güçlü, oral ve yüksek seçicilikli KIT tirozin kinaz inhibitörleri uzun süreli remisyon olasılığı sunmaktadır [4].""",

"FLT3 D835Y": """FLT3 D835Y, akut miyeloid lösemide (AML) FLT3 reseptörünün tirozin kinaz alanında (TKD) en sık görülen nokta mutasyonudur; 835. pozisyondaki aspartik asidin tirozine dönüşmesiyle reseptörü sürekli aktive eder [5]. FLT3 mutasyonları AML'lerin yaklaşık üçte birinde bulunur; en sık, juxtamembran bölgesindeki internal tandem duplikasyonu (ITD, ~%23) ve TKD nokta mutasyonlarıdır (~%10) [2][5]. Her iki mutasyon da FLT3'ü aktive etse de ITD taşıyan hastaların prognozu belirgin biçimde daha kötüdür; knock-in fare modellerinde D835Y'li fareler ITD'li farelere göre daha uzun yaşar ve daha az agresif miyeloproliferatif neoplazi geliştirir [5].

Klinik önemi açısından D835Y, seçici FLT3 inhibitörlerine karşı kazanılmış direncin başlıca nedenlerinden biridir; FLT3-ITD'li hücrelerde inhibitör baskısı altında sekonder D835Y mutasyonu ortaya çıkabilir ve bu hücreler AC220 (quizartinib) ile sorafenibe yüksek direnç gösterir [4]. Ayrıca NPM1c mutasyonu, FLT3-TKD'nin hücre içi yerleşimini hücre yüzeyinden endoplazmik retikuluma kaydırarak STAT5'i aktive eder; bu birliktelik AML'de prognostik önem taşır [1].

Tedavi geliştirmede D835Y aracılı direnci aşmak için ikili inhibitörler üzerinde çalışılmaktadır; FLT3/Aurora A inhibitörü CCT245718, FLT3-ITD/D835Y çift mutantı taşıyan hücrelerde direnci aşmıştır [3]. Benzer şekilde bir imidazo[1,2-a]piridin türevi (bileşik 1), hem FLT3-ITD hem BCR-ABL yollarını inhibe ederek FLT3-ITD/D835Y ve FLT3-ITD/F691L sekonder mutantlarını güçlü biçimde baskılamıştır [2].""",

"MYD88 L265P": """MYD88 L265P, MYD88 proteininin 265. pozisyonundaki lösinin proline dönüşmesiyle oluşan bir sürücü mutasyondur ve B-hücreli hematolojik malignitelerde görülür [1]. Waldenström makroglobulinemisi (WM) vakalarının yaklaşık %90'ında bulunur; bu, tek bir amino asit değişiminin bir kanserin neredeyse tamamında görüldüğü ender bir örnektir ve WM'yi tek nedensel mutasyon çalışmaları için model hastalık yapar [1]. Mutasyon ayrıca aktive B-hücre (ABC) tipi difüz büyük B-hücreli lenfomalarda (DBBHL) ve IgM monoklonal gammopatilerde önemli oranda görülür [1].

Waldenström makroglobulinemisinde L265P mutasyonu hastaların %90'ından fazlasında ve çoğu IgM MGUS hastasında saptanır; ancak tanı için zorunlu değildir [3]. Mutasyon NF-κB yolunu aktive ederek hastalığı sürükler; tedavide Bruton tirozin kinaz (BTK) inhibitörleri (ör. zanubrutinib) ve kemoimmünoterapi ön plandadır [1][3].

Difüz büyük B-hücreli lenfomada MYD88 L265P ile CD79B mutasyonlarının birlikte bulunması, MCD adı verilen genetik bir alt grubu tanımlar; bu alt grup kötü prognoz ve ekstranodal (özellikle immün-ayrıcalıklı bölge) tutulumuyla karakterizedir; kronik aktif B-hücre reseptörü sinyali ile onkojenik MYD88 mutasyonu patolojik NF-κB aktivasyonunu birlikte sürükler [2]. Merkezi sinir sistemi, göz ve testis gibi immün-ayrıcalıklı bölgelerde ortaya çıkan primer büyük B-hücreli lenfomalar sıklıkla MYD88 (L265P) ve CD79B ko-mutasyonları taşır ve BTK inhibitörleri, immünomodülatör ajanlar ve immünoterapiye duyarlı olabilir [5]. L265P'ye yönelik peptit temelli immünoterapi de araştırılan tedavi stratejileri arasındadır [1].""",

"CFTR F508del": """CFTR F508del, kistik fibrozis (KF) hastalarının %80'inden fazlasının taşıdığı, epitel hücrelerinin klorür kanalı olan CFTR proteinindeki en sık mutasyondur [1]. Üç nükleotitlik bir delesyon olan bu mutasyon CFTR'nin katlanmasını bozar ve protein, endoplazmik retikulum ilişkili yıkım (ERAD) ile parçalanarak hücre yüzeyine ulaşamaz [1].

Tedavi büyük ölçüde CFTR modülatörlerine dayanır: küçük moleküllü "düzelticiler" (correctors) farmakolojik şaperon gibi davranarak CFTR-F508del'i ERAD'dan kurtarır; tezakaftor (VX-661) ve elexakaftor (VX-445), proteini yıkıma dirençli katlanma durumlarında kararlı kılar [1]. Faz 3 çalışmada, F508del için homozigot hastalarda elexakaftor + tezakaftor + ivakaftor üçlü kombinasyonu, tezakaftor + ivakaftora kıyasla beklenen FEV1 yüzdesini yaklaşık 10 puan artırmış, ter klorürünü belirgin biçimde düşürmüş ve solunumla ilişkili yaşam kalitesini iyileştirmiştir; kombinasyon iyi tolere edilmiştir [3]. Bu tedavi en az bir F508del varyantı taşıyanlar için onaylıdır; F508del taşımayan hastalarda da Fransız erişim programında yarısından fazlası tedaviye yanıt vermiştir [2].

Genetik ve gelecek yaklaşımlar açısından, 5.058 KF hastasında yapılan tam CFTR gen dizilemesi kohortun %99,6'sında güncel veya gelişmekte olan tedavilerle hedeflenebilir en az bir varyant saptamıştır [4]. Kalıcı, tek seferlik bir tedavi hedefiyle prime editing (baştan düzenleme) yöntemi optimize edilerek, hasta kaynaklı hava yolu epitel hücrelerinde F508del %25'e varan oranda düzeltilmiş ve CFTR iyon kanalı işlevi yaban tip düzeyin %50'sinin üzerine çıkarılmıştır [5].""",

"AKT1 E17K": """AKT1 E17K, PI3K/AKT yolunun bir üyesi olan AKT1 proteininin pleckstrin homoloji alanında 17. pozisyondaki glutamatın lizinle değişmesiyle (Glu17Lys) oluşan bir sıcak nokta mutasyondur; meme, kolorektal ve over kanserlerinde görülür [2]. Mutasyon AKT1 kinazı aktive eder (Ser473/Thr308 fosforilasyonu) ve aşağı yönlü büyüme sinyallerini uyararak hücreleri dönüştürür [2][4].

Klinik ve tedavi açısından, NCI-MATCH çalışmasının EAY131-Y alt protokolünde AKT1 E17K mutasyonlu metastatik tümörü olan hastalara pan-AKT inhibitörü kapivasertib verilmiş; objektif yanıt oranı %28,6 bulunmuş, en sık meme (%51) ve jinekolojik (%31) kanserler yer almış ve altı aylık progresyonsuz sağkalım %50 olmuştur [1]. AKT1 E17K taşıyan meningiom hücre modellerinde AKT inhibitörü AZD5363, hücre çoğalmasını azaltıp fare sağkalımını uzatmıştır [4].

İşleve bağlı ikili bir rolü vardır: AKT1 E17K melanomda beyin metastazını, odak adezyon kinazının (FAK) aktivasyonu yoluyla artırır ve invazyonu güçlendirir; bu etki AKT veya FAK inhibisyonuyla azalır [3]. Buna karşın bazı bağlamlarda AKT1 E17K, β-katenin sinyalini baskılayıp E-kaderin ifadesini artırarak hücre göçünü ve invazyonu paradoksal olarak engeller; bu nedenle AKT inhibitörlerinin bazı genetik zeminlerde metastatik ilerlemeyi hızlandırabileceği öne sürülmüştür [2][5].""",

"ABL1 T315I": """ABL1 T315I, kronik miyeloid lösemide (KML) Philadelphia kromozomunun oluşturduğu BCR::ABL1 füzyon onkoproteininde ortaya çıkan bir nokta mutasyonudur [1]. KML, t(9;22) translokasyonu sonucu ABL1 ve BCR genlerinin birleşmesiyle karakterizedir ve tedavisinde tirozin kinaz inhibitörleri (TKİ) kullanılır [1].

T315I, ilaç bağlanma cebindeki "bekçi" (gatekeeper) kalıntısını değiştirir ve tedavi sırasında bir nokta mutasyonu olarak ortaya çıkarak kazanılmış dirence yol açar; bu mutasyonu taşıyan hastalar kötü prognoza sahiptir [3]. T315I taşıyan hastalar mevcut TKİ'lerin çoğuna dirençlidir; yalnızca ponatinib, asciminib ve olverembatinib bu mutasyona karşı etkilidir [1].

Tedavi seçenekleri açısından ponatinib, T315I dahil tüm tek-mutasyonlu BCR::ABL1 varyantlarını inhibe eder; Philadelphia kromozomu pozitif akut lenfoblastik lösemide birinci basamakta imatinibe kıyasla daha yüksek minimal kalıntı hastalığı-negatif tam yanıt oranı sağlamıştır [5]. Asciminib, ABL miristoil cebini özgül olarak hedefleyen (STAMP) ilk onaylı BCR::ABL1 inhibitörüdür [4] ve en az iki önceki TKİ almış ya da T315I mutasyonu taşıyan KML hastaları için onaylıdır [2]. En az iki TKİ'ye direnç gösteren ya da ileri evre hastalarda allojenik kök hücre nakli önemli bir seçenek olmayı sürdürür [1].""",

"IDH2 R140Q": """IDH2 R140Q, izositrat dehidrogenaz 2 enzimindeki en sık görülen mutasyondur ve lösemi gelişimini (lökomojenezi) tetikler; sitogenetik olarak normal akut miyeloid löseminin (AML) %15'inden fazlasında IDH2 mutasyonları görülür [1][2]. Mutant enzim, onkometabolit 2-hidroksiglutarat birikimine yol açar [4].

Mekanizma açısından IDH2/R140Q, TF-1 hücrelerini sitokinden bağımsız çoğalmaya dönüştürür; bu, STAT3 ve STAT5'in anormal sürekli fosforilasyonu ve otokrin GM-CSF, LIF ve OSM salgısıyla ilişkilidir [1]. STAT3/5 fosforilasyonunun inhibisyonu bu sitokinden bağımsız çoğalmayı baskılar ve AML tedavisinde yeni bir strateji olabilir [1]. Zebra balığı modelleri IDH2R140Q AML'sinin morfolojik ve moleküler özelliklerini taklit eder ve lösemik fenotip quizartinib ve enasidenib ile hafifletilebilir [2].

Tedavi açısından IDH2/R140Q'yu hedeflemek klinikte umut verici sonuçlar vermiştir; ancak tedavi edilen hastaların %12'sinde direnç gelişir [1]. Mutant IDH2'yi hedefleyen yeni inhibitörler moleküler doking yöntemleriyle araştırılmaktadır [4].""",

"DNMT3A R882H": """DNMT3A R882H, DNA metiltransferaz 3A enzimindeki en sık nokta mutasyondur ve klonal hematopoezin (CH) en yaygın biçimini sürükleyerek akut miyeloid lösemi (AML) riskini artırır [1]. Mutasyon, DNA metilasyon örüntüsünü bozarak lösemiyi başlatır [3].

Rol ve mekanizma açısından DNMT3A R882 mutasyonları AML'de erken, lösemi öncesi klonal hematopoez aşamasında ortaya çıkar; CRISPR ile bu mutasyonların düzeltildiği çalışmalar, mutasyonun lösemi başlangıcı için gerekli olduğunu ancak yerleşmiş hastalığın sürdürülmesi için büyük ölçüde gereksiz olduğunu göstermiştir [3]. Mutasyon, lösemi kök hücresi sıklığının artmasıyla ilişkilidir [3]. Klonal hematopoez ayrıca inflamatuar kemik kaybını (periodontit) ve IL-17 bağımlı inflamasyonu teşvik eder; bu etki rapamisinle baskılanabilir [2].

Tedaviye direnç ve önleme açısından DNMT3A R882H taşıyan AML hücreleri daunorubisine dirençlidir; bu direnç NRF2/NQO1 yolunun aktivasyonuyla ilişkilidir ve NRF2 inhibisyonu duyarlılığı artırır [5]. Mutant kök/progenitör hücreler oksidatif fosforilasyona daha bağımlıdır; SLC25A1 ve kompleks I inhibitörleri (metformin dahil) klonal genişlemeyi baskılar ve metformin kullanan bireylerde DNMT3A-R882-mutant klonal hematopoez prevalansı belirgin biçimde düşük bulunmuştur [1].""",

"PDGFRA D842V": """PDGFRA D842V, gastrointestinal stromal tümörlerde (GİST) görülen ve PDGFRA geninin ekson 18'indeki (aktivasyon ilmiği) 842. pozisyonda aspartik asidin valine dönüşmesiyle oluşan bir mutasyondur [2]. GİST vakalarının yaklaşık %5-10'u PDGFRA mutasyonu taşır ve bunların en sık görüleni D842V'dir [2].

Klinik önemi açısından D842V, başta imatinib ve sunitinib olmak üzere konvansiyonel tirozin kinaz inhibitörlerine birincil (intrinsik) direnç sağlar; bu nedenle uzun süre bu alt grup için etkili bir ilaç bulunmuyordu [2][4].

Tedavide avapritinib, aktivasyon ilmiği mutantlarını (D842V dahil) seçici olarak inhibe etmek için tasarlanmış bir kinaz inhibitörüdür ve bu mutasyonu taşıyan GİST için ilk onaylı ajandır [4][5]. Faz 1 NAVIGATOR çalışmasında D842V-mutant GİST hastalarında %88 genel yanıt oranı sağlamıştır (%9 tam, %79 kısmi yanıt) [1]; Avrupa İlaç Ajansı değerlendirmesinde genel yanıt oranı %95 ve ortanca yanıt süresi 22,1 ay bildirilmiştir [3]. Gerçek dünya verilerinde de avapritinib progresyonsuz ve genel sağkalımı uzatmıştır [4]. En sık yan etkiler bulantı, yorgunluk, anemi ve hafif bellek bozukluğudur; nadiren ciddi ensefalopati ve kanama görülebilir [3].""",

"RET M918T": """RET M918T, RET proto-onkogeninin kodladığı reseptör tirozin kinazı sürekli aktive eden bir mutasyondur ve medüller tiroid karsinomunun (MTK) başlıca sürücülerindendir [1][2]. Germline (kalıtsal) düzeyde çoklu endokrin neoplazi tip 2B bağlamında kalıtılabilir ya da yaşam boyu somatik olarak edinilebilir; MEN2B vakalarının %95'inde ve sporadik MTK'lerin yaklaşık %50'sinde bulunur [5]. RET nokta mutasyonları MTK'lerin %25-65'inde saptanır [2].

Klinik seyir açısından RET M918T'ye bağlı MTK ilerlemesi, hastalık başlangıcı ve çok odaklı büyüme farkları hesaba katıldığında kalıtsal ve sporadik hastalıkta benzerdir; ancak kalıtsal MTK daha erken gelişir ve daha sık çok odaklıdır [1]. Dolaşımdaki hücre dışı DNA'da (cfDNA) RET M918T saptanması kötü genel sağkalımla güçlü biçimde ilişkilidir ve kalsitonin ikilenme süresinden daha güvenilir bir prognostik belirteç olabilir [4].

Tedavide vandetanib ve kabozantinib gibi çoklu kinaz inhibitörleri ileri MTK'de hastalık ilerlemesini yavaşlatan ilk etkili ajanlardı; sonrasında yüksek seçicilikli RET inhibitörleri selperkatinib ve pralsetinib, daha yüksek etkinlik ve daha az hedef-dışı yan etkiyle kliniğe girmiştir [2]. Ayrıca RET M918T neoepitopunu hedefleyen mühendislik ürünü T hücreleri (adoptif hücre tedavisi) preklinik olarak araştırılmaktadır [3].""",

"ESR1 Y537S": """ESR1 Y537S, östrojen reseptörü alfa'yı kodlayan ESR1 genindeki en önemli aktive edici mutasyonlardan biridir; reseptörün östrojenden bağımsız (ligandsız) aktivasyonuna yol açar ve metastatik meme kanserinde endokrin tedaviye dirençle ilişkilidir [2][4]. ESR1 mutasyonları ileri, östrojen reseptörü pozitif meme kanserinin yaklaşık %10'unda bulunur; D538G en sık, Y537S ikinci sıradadır [2].

Klinik önemi açısından Y537S saldırgan hastalık biyolojisiyle ilişkilidir; BOLERO-2 çalışmasında Y537S taşıyan hastaların genel sağkalımı yaban tipe göre daha kısa bulunmuştur [4]. Diğer aktive edici mutasyonların aksine yalnızca Y537S gibi seçili mutantlar fulvestrant direncine yol açacak ölçüde etki gösterir [2]. Ayrıca Y537S ve D538G, CDK4/6 inhibitörlerine dirence de katkıda bulunur [1].

Tedavide Y537S, mevcut östrojen reseptörü antagonisti fulvestranta göreli direnç gösterir; AZD9496 gibi daha güçlü ve biyoyararlanımı yüksek yeni nesil antagonistler bu mutantı daha etkili baskılayabilir [2]. Östrojen reseptörünü yıkan oral bir PROTAC olan vepdegestrant (ARV-471), Y537S taşıyan ve palbosiklibe dirençli modellerde tümör gerilemesi sağlamış ve CDK4/6, mTOR veya PI3K inhibitörleriyle kombinasyonda etkili bulunmuştur [5].""",

"PIK3CA E545K": """PIK3CA E545K, PI3K enziminin katalitik alt birimini kodlayan PIK3CA geninin ekson 9'undaki en sık görülen sıcak nokta mutasyondur; meme kanserinde H1047R'den sonra ikinci en sık PIK3CA mutasyonudur (tüm PIK3CA mutasyonlarının %17'si) [2]. Serviks (rahim ağzı) kanseri ve kolorektal kanserde de sık görülür [1][3].

Klinik önemi açısından İran'daki kolorektal kanser hastalarında %10,7 sıklıkta saptanmış; tümör farklılaşması ve TNM evresiyle ilişkili bulunmuş ve daha kötü genel sağkalımın bağımsız bir göstergesi olmuştur [3]. Serviks kanserinde E545K radyoterapiye direnç sağlar; bunu SIRT4'ü baskılayıp glutamin metabolizmasını artırarak [1] ve AKT/GSK3β/β-katenin yolunu aktive edip β-kateninin çekirdekte birikmesini sağlayarak yapar [4].

Tedavi yaklaşımları açısından PI3K inhibitörü BYL719 (alpelisib), mTOR inhibitörlerinin aksine glutamin metabolizmasını baskılayarak radyoterapiyle belirgin sinerji gösterir [1]; β-kateninin hedeflenmesi (XAV939) de E545K'lı hücrelerde radyo-duyarlılığı geri kazandırır [4]. Papiller tiroid kanseri modelinde PIK3CA E545K, BRAF V600E ile bir arada farklılaşma belirteçlerini azaltarak daha az farklılaşmış, saldırgan bir fenotipe geçişi destekler [5].""",

"KRAS G12V": """KRAS G12V, kanserde en sık ikinci KRAS mutasyonudur; ancak henüz bu mutasyonu doğrudan hedefleyen onaylı bir inhibitör yoktur [1]. Pankreas duktal adenokarsinomlarında (PDAK) KRAS mutasyonlarının yaklaşık %34'ünü oluşturur ve bu mutasyonlar sistein-reaktif KRAS G12C inhibitörleriyle (sotorasib, adagrasib) hedeflenemez [3].

Hedefleme yaklaşımları açısından G12V gibi mutasyonlar, KRAS'ı çalıştıran guanin nükleotit değişim faktörü SOS1'in (Son of Sevenless 1) inhibisyonuyla dolaylı olarak hedeflenebilir [3]. Doğrudan hedefleme için EGFR'ye yönlendirilen bir RNA interferans molekülü (EFTX-G12V), KRAS G12V'ye yüksek seçicilik gösterip pan-KRAS hedeflemeye üstünlük sağlamıştır [1].

İmmünoterapi açısından KRAS G12V mutant neoantijeni HLA-A*11:01 bağlamında sunulur ve buna özgü T hücresi reseptörleriyle (TCR) donatılmış T hücreleri, mutasyonu taşıyan tümör hücrelerine karşı sitotoksik etki gösterir [2]. G12V mutant peptidi, yaban tip peptidden farklı bir konformasyon alır ve bu, TCR'nin seçici tanımasını sağlar [2]. Ayrıca KRAS G12V, KRAS G12C inhibitörlerine karşı tedavi sırasında ortaya çıkan bir direnç mekanizması olarak da saptanmıştır [5].""",

"HFE C282Y": """HFE C282Y, kromozom 6p'de yer alan ve demir emilimini düzenleyen HFE genindeki en sık patojenik varyanttır; kalıtsal hemokromatoz büyük ölçüde C282Y homozigotluğundan (iki kopya) kaynaklanır [1][3]. Homozigot bireylerde transferrin satürasyonu ve serum ferritin düzeyleri yükselir; bu, vücutta demir birikimini yansıtır [1].

Kanser riski açısından UK Biobank kohortunda C282Y homozigot erkeklerde primer karaciğer (hepatik) malignitesi riski belirgin biçimde artmıştır (HR 10,5); 75 yaşına dek karaciğer kanseri riski %7,2 iken varyant taşımayan erkeklerde %0,6'dır; bu ilişki kadınlarda istatistiksel olarak anlamlı bulunmamıştır [3]. Meta-analizler C282Y varyantını homozigot modelde meme kanseri (OR 2,06) [2] ve resesif modelde kolorektal kanser (OR 2,00) riski artışıyla ilişkilendirmiştir [5].

Diğer ilişkiler açısından metabolik sendrom bileşenleriyle (diyabet, hipertansiyon, lipid düzeyleri) yapılan meta-analizde anlamlı bir ilişki bulunmamıştır [4]. Trombosit sayısı, çalışılan HFE genotipleriyle anlamlı biçimde ilişkili değildir; anormal trombosit sayısı olan homozigot bireyler siroz açısından değerlendirilmelidir [1].""",

"SF3B1 K700E": """SF3B1 K700E, RNA kırpma (splicing) mekanizmasının bir bileşeni olan SF3B1 (spliceosome factor 3b subunit 1) proteinindeki en sık görülen mutasyondur ve hematolojik malignitelerde, özellikle miyelodisplastik sendromda (MDS) saptanır [1][2]. Mutasyon, SF3B1'in SUGP1 proteiniyle etkileşimini bozarak alternatif 3' kırpma bölgelerinin anormal aktivasyonuna ve yaygın, hatalı dal-noktası (branchpoint) tanımasına yol açar [4].

MDS'deki rolü açısından SF3B1 K700E, kemik iliğinde halka sideroblastların (ring sideroblast) oluşumunu doğrudan tetikler; bunu ABCB7 ve ALAS2 genlerinin ifadesini ve ABCB7'nin doğru kırpılmasını bozarak yapar; ABCB7 kaybı demir-kükürt kümesi taşınmasını engelleyerek halka sideroblast oluşumuna yol açar [2]. Prognoz açısından SF3B1 mutasyonları MDS'de genellikle olumlu kabul edilir; ancak bir çalışma, yalnızca K700E mutasyonunun (diğer kodonlardaki mutasyonların değil) bağımsız olarak daha iyi genel sağkalım öngördüğünü göstermiştir [3].

Diğer etkiler açısından K700E, hücre döngüsü düzenleyicilerinin (ör. ARPP19) kırpılmasını yeniden şekillendirerek mitotik ilerlemeyi etkiler; ARPP19-uzun izoformunun yüksekliği AML kohortunda daha kötü genel sağkalımla ilişkilidir [5]. Ayrıca düzenleyici T hücrelerinde (Treg) Anapc13'ün hatalı kırpılması yoluyla bağışıklık yanıtını bozarak otoimmün fenotiplere yol açabilir [1].""",

"TERT promoter C228T": """TERT promoter C228T, telomeraz ters transkriptaz (TERT) geninin promotör bölgesindeki iki sıcak nokta mutasyondan biridir (diğeri C250T); bu mutasyonlar TERT ifadesini artırarak telomeraz aktivitesini yükseltir [1][2]. Glioblastomada en sık görülen mutasyondur ve gliom gelişiminin en erken olaylarından biridir [1].

Mekanizma açısından C228T, GA-Binding Protein'i (GABP) bölgeye çağırarak düşük düzeyde TERT ifadesine yol açar; bu, telomerler kısaldığında hücrelere büyüme avantajı sağlar ve kısa telomerlerin korunmasını sürdürür [1]. Oligodendrogliomlarda TERT promotör mutasyonları IDH1/2 mutasyonu ve 1p/19q ko-delesyonuyla birlikte görülür; C228T ve C250T genellikle birbirini dışlar [4].

Klinik önemi açısından baş-boyun skuamöz hücreli karsinomunda C228T mutasyonu, daha kısa hastalıksız sağkalım (%20,0'a karşı %63,0) ve genel sağkalım (%16,7'ye karşı %45,1) ile ilişkilidir; bu nedenle prognostik bir biyobelirteç olabilir [2]. Papiller tiroid kanserinde BRAF V600E ile birlikte bulunması yüksek riskli kabul edilir ve uzun süreli nüks takibi gerektirir [3]. Buna karşın BRAF V600E-pozitif Langerhans hücreli histiyositozda TERT promotör mutasyonları saptanmaz; bu, mutasyonun her BRAF V600E-pozitif tümörde rol oynamadığını gösterir [5].""",

"GNAQ Q209L": """GNAQ Q209L, heterotrimerik G proteininin alfa alt birimini kodlayan GNAQ genindeki aktive edici bir mutasyondur ve reseptörü sürekli aktif hale getirir [1]. Üveal (göz içi) melanomların yaklaşık %80-90'ı, GNAQ ya da homolog GNA11 genlerinde (çoğunlukla Q209 pozisyonunda) birbirini dışlayan mutasyonlar taşır; bu mutasyonlar tümör başlangıcı ve ilerlemesini sürükler [2][3]. Melanositlerde GNAQ/11 Q209L ifadesi tek başına metastatik melanom oluşturmaya yeterlidir [3].

Görülme yerleri açısından GNAQ Q209L, üveal melanom dışında leptomeningeal melanositik neoplazileri (kranial/spinal melanositomlar ve melanomlar) de sürükler; bu, mutasyonun çok yetenekli nöral krest hücrelerinde ifade edilmesiyle oluşur [1].

Tedavi ve hedefleme açısından bu onkojenik G proteinlerini doğrudan hedefleyen bilinen bir ilaç yoktur [3]. Yaklaşımlar arasında GNAQ Q209L transkriptlerini seçici olarak susturan siRNA/rAAV temelli allel-özgül stratejiler [2] ve Gαq'yu katlayan şaperon Ric-8A'nın inhibisyonu ya da forbol ester uygulaması yoluyla mutant proteinin bolluğunu azaltmak yer alır [3]. Ayrıca GNAQ/11 Q209L varyantı, Q209P'ye kıyasla HLA'ya daha güçlü bağlanır ve bireylerin çoğunda sunulabilir; bu, üveal melanom için neoantijen aşıları gibi immünoterapötik araçlara olanak tanıyabilir [4].""",

"CTNNB1 S45F": """CTNNB1 S45F, β-katenini kodlayan CTNNB1 geninin ekson 3'ündeki bir mutasyondur; desmoid tip fibromatoz (desmoid tümör) vakalarının çoğunda β-katenin mutasyonları görülür ve S45F, T41A ile birlikte en sık değişimlerdendir [1][2]. Mutasyon β-kateninin çekirdekte birikmesine yol açar; S45F taşıyan olguların tümü güçlü çekirdek β-katenin ifadesi gösterir [1].

Klinik önemi açısından S45F, diğer CTNNB1 mutasyonlarına (ör. T41A) kıyasla cerrahi sonrası daha yüksek nüks olasılığı ve sistemik tedavilere daha fazla dirençle ilişkilidir [2]. COX-2 seçici inhibitör meloksikam ile tedavide S45F taşıyan tüm olgular kötü yanıt (hastalık ilerlemesi) göstermiştir; diğer mutasyonların yanıt üzerine etkisi olmamıştır [1].

Cerrahi tedavi gören hastalarda S45F mutasyonu (HR 5,25) ve ekstremite yerleşimi, lokal nüks için bağımsız risk faktörleridir; bu iki etkeni taşıyanların nüks riski belirgin biçimde yüksektir [3]. Bu nedenle CTNNB1 mutasyon durumu, desmoid tümörlerde tedavi kararına yardımcı prognostik bir biyobelirteç olabilir [1][3].""",

"POLE P286R": """POLE P286R, DNA polimeraz epsilon'un (POLE) düzeltme-okuma (proofreading) işlevini bozan bir sıcak nokta mutasyondur; "ultra-mutatör" bir fenotipe yol açarak tümör mutasyon yükünü (TMB) çok yükseltir [1][4]. Endometriyum (rahim) kanserinin tanımlayıcı özelliklerinden biridir ve kolorektal kanserde de görülür [2][4].

Mekanizma ve immünojenite açısından P286R, DNA hasarını artırıp onarımını baskılayarak genomik kararsızlığa ve sitoplazmik DNA birikimine yol açar; bu da cGAS-STING yolunu aktive ederek kansere karşı içsel bağışıklığı uyarır ve endometriyal tümör oluşumunu baskılar [2]. Yüksek TMB ve kanser hücrelerine sitotoksik T hücresi infiltrasyonu bu tümörleri immünojenik kılar [1][2].

Klinik önemi açısından POLE P286R, mikrosatellit kararlı (MSS) olmasına rağmen immün kontrol noktası blokajına duyarlı, hipermutasyonlu bir kanser alt sınıfını tanımlar ve immünoterapi için potansiyel bir genomik biyobelirteçtir [3][4]. Erken başlangıçlı kolorektal kanserlerin bir kısmında (%7,2) saptanmış, geç başlangıçlılarda ise görülmemiştir [4]. Bununla birlikte tümör içi mutasyonel heterojenite ve azalmış antijen sunumu, yüksek TMB'ye rağmen immün dirence katkıda bulunabilir; STING agonistleri veya p53 indüksiyonu duyarlılığı artırabilir [1].""",

"TP53 R248Q": """TP53 R248Q, tümör baskılayıcı p53 proteininin DNA-bağlanma alanındaki en sık görülen sıcak nokta mutasyonlardan biridir; R248 kalıntısı normalde DNA'nın küçük oluğuyla doğrudan etkileşir [5]. Mutasyon, DNA-bağlanma alanında mutasyon bölgesinden uzak bölgelerde bile konformasyon değişikliklerine yol açar ve çinko-bağlanma cebini etkileyerek dominant-negatif etki gösterir; ayrıca proteinin kısmen açılıp agregasyona eğilim kazanmasına neden olabilir [5].

Kazanılmış işlev (gain-of-function) açısından R248Q, yüksek dereceli seröz over karsinomunda aşırı ifade edildiğinde AKT fosforilasyonunu artırır ve EGFR sinyalini sürdürerek EGFR/MDM2 hedefli tedavilere yanıtı değiştirir [3]. Çocukluk çağı akut lenfoblastik lösemisinde TP53 mutasyonu kemoterapi direnciyle ilişkilidir; hücre modellerinde R248Q, p53 transaktivasyon aktivitesini bozarak kemoterapötik ajanlara ve ışınlamaya direnç kazandırmıştır [2].

Diğer etkiler açısından glioblastom hücrelerinde TP53 R248Q hücre yapışmasını artırır ve özellikle hiyalüronik asit ile kondroitin sülfat üzerinde göçü belirgin biçimde teşvik eder; IDH1 R132H ile birlikte bulunduğunda en yüksek göç hızı gözlenir [1].""",

"KRAS G13D": """KRAS G13D, kolorektal kanserde (KRK) sık görülen ve kötü prognozla ilişkili, kendine özgü biyolojik davranış gösteren bir KRAS mutasyonudur [1]. Biyokimyasal olarak G13D, aktif bölgedeki elektrostatik yük dağılımını değiştirerek diğer KRAS mutantlarına kıyasla hızlı nükleotit değişim kinetiği gösterir [5].

Klinik önemi ve direnç açısından KRAS mutasyonları, EGFR'yi hedefleyen monoklonal antikorlara (setuksimab) doğal direnç sağlar [2]. G13D-mutant KRK'lerde yalnızca bu alt tipte aktive olan bir HER2-ELF3-KRAS ekseni, saldırgan onkojenik özellikleri ve setuksimab direncini sürükler; bu eksenin (ör. YK1 ile ELF3-MED23 etkileşiminin) bozulması hücreleri setuksimaba duyarlı hale getirir [1].

Tedaviyi güçlendirme açısından doğal bir bileşik olan honokiol, SNX3-retromer kompleksini bozarak ve RAS'ın GDP'den GTP'ye dönüşümünü engelleyerek G13D-mutant KRK modellerinde setuksimab duyarlılığını artırır [2]. Ayrıca G13D, KRAS G12C inhibitörlerine karşı tedavi sırasında ortaya çıkan kazanılmış direnç mekanizmalarından biri olarak da saptanmıştır [3][4].""",

"FGFR3 S249C": """FGFR3 S249C, fibroblast büyüme faktörü reseptörü 3'ü (FGFR3) kodlayan gendeki en sık görülen tekrarlayan mutasyondur ve mesane kanserinde başlıca sürücülerdendir [1][3]. Düşük dereceli, invaziv olmayan papiller ürotelyal karsinomların %60'ından fazlası aktive edici FGFR3 nokta mutasyonları taşır [3]. Mutant S249C proteini kararlı homodimerler oluşturur ve sürekli fosforillenir [3].

Kökeni açısından S249C (TCC→TGC) bir APOBEC motifini temsil eder ve muhtemelen APOBEC aracılı mutasyonel süreçten kaynaklanır; bu, mesane tümörlerinde neden bu kadar sık görüldüğünü açıklar [1].

Klinik önemi ve tedavi açısından FGFR3 S249C mesane kanserinde onkojenik bir bağımlılık oluşturur; shRNA ile susturulması hücre çoğalmasını ve klonojenik kapasiteyi azaltır ve bu, hedefe yönelik inhibisyonun terapötik değerini destekler [3]. Ürotelyal karsinomda erdafitinib gibi FGFR inhibitörleri onaylı hedefli tedavilerdir; ancak yanıt oranları FGFR3 değişiminin tipine bağlıdır: FGFR3-TACC3 füzyonları daha yüksek yanıtla ilişkiliyken S249C mutasyonu yanıtla negatif korelasyon göstermiştir [2]. Fare modellerinde S249C, erken evrede akut inflamasyonu baskılayarak mesane tümör gelişimini artırır [5].""",

"MPL W515L": """MPL W515L, trombopoietin reseptörünü kodlayan MPL genindeki bir mutasyondur ve JAK2 V617F-negatif miyeloproliferatif neoplazilerde (özellikle esansiyel trombositoz ve primer miyelofibroz) görülür [5]. Reseptörü aktive ederek hastalığı sürükler; bir çalışmada ET ve PMF hastalarında MPL W515L/K sıklığı %2,6, JAK2 V617F-negatif hastalarda ise %4,8 bulunmuş ve saptanan tüm olgular JAK2 V617F-negatif olmuştur [5]. Bu nedenle W515L/K varlığı, Philadelphia kromozomu ya da JAK2 V617F taşımayan MPN hastalarında klonaliteyi göstermede yardımcı olabilir [5].

Mekanizma açısından MPL W515L, THOC5'in tirozin fosforilasyonu yoluyla MYC ifadesini düzensizleştirerek hücre hareketini (kemokinez) artırır ve sfingozin-1-fosfat üretimiyle bağlantılı TGFβ salgısını indükler; bunlar terapötik hedefler sunar [3]. Fare modellerinde MPL W515L bağırsakta inflamasyonu ağırlaştırır ve kaspaz1/IL-1β yolunu aktive eder [1].

Tedavi açısından MPN'lerin sekonder akut miyeloid lösemiye dönüşümünde artan DUSP6 ifadesi rol oynar; DUSP6 inhibisyonu, Jak2V617F ve MPLW515L MPN fare modellerinde hastalık gelişimini güçlü biçimde baskılar ve JAK2 inhibitörü direncini aşabilir [4].""",

"AR T878A": """AR T878A (eski adıyla T877A), androjen reseptörünün (AR) ligand-bağlanma alanındaki bir mutasyondur ve prostat kanserinde hormonal tedavilere dirençle ilişkili sıcak nokta değişimlerden biridir [4]. AR amplifikasyonu, aşırı ifadesi ve L702H, W742L/C, H875Y, F877L, T878A gibi mutasyonlar ileri prostat kanserinde tedavi direncinin başlıca nedenlerindendir; bu mutasyonlar reseptörün ligand bağlama afinitesini değiştirir [4].

Klinik önemi açısından T878A, reseptörün ligand-bağlanma cebini genişleterek yanıtını değiştirir [1]. Abirateron ile tedavi edilen kastrasyona dirençli prostat kanseri hastalarının plazmasında, ilerleme anında %13 oranında T878A veya L702H değişimi ortaya çıkar; tedavi öncesi bu değişimleri (ya da AR kazanımını) taşıyanlarda PSA yanıtı belirgin biçimde daha düşük ve sağkalım daha kötüdür [2].

Tedavi geliştirme açısından T878A ile birlikte F877L mutasyonu, enzalutamid ve apalutamid gibi ikinci nesil antagonistleri agoniste dönüştürebilir; bu durum özellikle F877L/T878A çift mutantında belirgindir [1][5]. Buna karşın pruxelutamid bu mutantlarda agonist etki göstermez ve inhibitör aktivitesini korur [1]. Ayrıca T878A-mutant AR'yi seçici hedefleyen yeni bir antagonist (S-94), yaban tip AR'ye kıyasla yaklaşık 50 kat daha güçlü etkiyle klinikte önemli T878A-ilişkili mutantları baskılamıştır [3].""",

"PTEN R130Q": """PTEN R130Q, en sık mutasyona uğrayan tümör baskılayıcı genlerden biri olan PTEN'in fosfataz alanındaki sık görülen bir sıcak nokta mutasyondur [3]. PTEN mutasyona uğradığında işlevini yitirir ve tümör baskılama etkisini kaybeder [2]. R130Q, PTEN'in PIP2'ye bağlanma yeteneğini bozarak defosforilasyon sürecini engeller [5].

Görülme yerleri açısından endometriyum (rahim) kanserinde en sık görülen onkojenik PTEN missense mutasyonları R130G ve R130Q'dur [3]. Hepatoselüler karsinom örneklerinin önemli bir kısmında (40 örneğin 26'sında) R130Q saptanmıştır [2]. Ayrıca glioblastom ve pineal bölge tümörleri gibi kanserlerde de görülür [1][4].

Klinik önemi ve tedavi açısından PTEN alterasyonları mTORC1 inhibitörleriyle (ör. everolimus) tedavi edilebilir; pineal bölgenin papiller tümöründe PTEN R130Q ve kromozom 10 kaybı taşıyan bir hastada tek başına everolimus tedavisiyle tümör gerilemesi bildirilmiştir [1]. Glioblastomda bazı fosfataz-alanı missense mutasyonları ('kenar mutasyonları') hücre çeperine yerleşerek invazyonu artırır; bu invaziv fenotip PI3K/Akt inhibitörlerinden etkilenmezken mikrotübül inhibitörleriyle bozulur ve mutasyona özgü bir tedavi hedefi olabilir [4]. Doğrudan hedeflemenin zorluğu, mutant PTEN'in işlevinin geri kazandırılması (restorasyon) gerekliliğinden kaynaklanır [5].""",

"HRAS G12V": """HRAS G12V, RAS GTPaz ailesinin bir üyesi olan HRAS'ta 12. kodondaki glisinin valine dönüşmesiyle oluşan, sürekli aktif bir onkojenik mutasyondur; RAS proteinleri hücresel sinyal iletiminde moleküler anahtar olarak çalışır [4]. HRAS'taki 12 ve 13. kalıntıları etkileyen mutasyonlar hem somatik (kanser) hem de germline (gelişimsel bozukluk) bağlamda görülür [4].

Kanserdeki rolü açısından onkojenik HRAS G12V ifadesi, NIH 3T3 hücrelerinde hücre boyutu kontrolünü bozmaya tek başına yeterlidir; bu, kanser hücrelerindeki boyut kusurlarının doğrudan onkojenik sürücülerin sonucu olduğunu düşündürür [3]. c-Myc ile birlikte en güçlü tümör oluşturma etkisini RAS sinyal yolu aktive olduğunda gösterir [2]. Orofarengeal skuamöz hücreli karsinomda HRAS G12V, laktat varlığında MEK/ERK yolunu aktive ederek immün kaçışa katkıda bulunan PD-L1 ifadesini artırır [5]. Mozaik deride HRAS G12V-mutant hücreler yaban tip hücreleri geçse de, yaralanma sonrası yaban tip hücrelerin EGFR sinyaline yanıt vererek çoğalması bu anormal büyümeyi baskılar [1].

Gelişimsel bozukluk açısından HRAS'ın germline G12V mutasyonu Costello sendromuna (bir RASopati) neden olur; konjenital kalp anomalileri, gelişme geriliği, kansere yatkınlık ve erken yaşlanma (düşük kemik yoğunluğu) ile karakterizedir; fare modelinde artmış osteoklast oluşumu kemik kaybına katkıda bulunur ve MEK ile PI3K inhibitörleriyle azaltılabilir [4].""",

"ALK F1174L": """ALK F1174L, anaplastik lenfoma kinazı (ALK) kodlayan gende 1174. kodonda fenilalaninin lösine dönüşmesiyle oluşan bir nokta mutasyonudur ve reseptörü sürekli aktive eder [4]. Nöroblastomdaki en sık ALK somatik mutasyonlarından biridir ve kötü sağkalımın en güvenilir belirteci olan MYCN amplifikasyonuyla birlikte görülür [4].

Nöroblastomdaki rolü açısından fare modellerinde ALK F1174L ifadesi sempatik gangliyon progenitörlerinin çoğalmasını artırsa da tek başına nöroblastom oluşturmaya yetmez; ancak MYCN ile birlikte ifade edildiğinde, tek başına tümör yapmayan MYCN'nin onkojenik yeteneğini belirgin biçimde güçlendirerek ölümcül nöroblastoma yol açar [4]. Nöroblastom bağışıklık kaçışında NECTIN2-TIGIT ekseni kritik bir kontrol noktasıdır; TIGIT ve PD-L1 blokajının birlikte uygulanması kemoterapiye dirençli Th-ALKF1174L/MYCN modelinde tam yanıtlar sağlamıştır [2].

Diğer kanserler ve direnç açısından ALK F1174L, kutanöz skuamöz hücreli karsinomda tümör oluşumunu başlatabilir; onkojenik Kras G12D ve p53 kaybıyla işbirliği yaparak daha saldırgan bir fenotipe yol açar ve başlıca Stat3 üzerinden etki eder [3]. Ayrıca F1174L, ALK-translokasyonlu kanserlerde ALK kinaz inhibitörü krizotinibe kazanılmış direnç oluşturur; kimyasal olarak farklı bir ALK inhibitörü (TAE684) ve HSP90 inhibitörü 17-AAG bu mutasyonu taşıyan modellerde etkilidir [1][5].""",

}
